const COPY = {
  en: {
    defaults: {
      brandStorefront: "Brand Storefront",
      collection: "Collection",
      collectionNumber: "Collection {{count}}",
      product: "Product",
      category: "Category",
      card: "Card",
      stepNumber: "Step {{count}}",
      value: "Value",
      link: "Link",
      social: "Social",
      offer: "Offer",
      campaign: "Campaign",
      policy: "Policy",
      finalCtaAlt: "Final call to action",
      brandHeroMediaAlt: "Brand hero media",
    },
    masthead: {
      catalog: "Catalog",
      collections: "Collections",
      bestSellers: "Best Sellers",
      policies: "Policies",
      support: "Support",
      brandStores: "Brand Stores",
      navigationAria: "Brand market navigation",
      storefront: "Brand Storefront",
      storefrontPreview: "Brand Storefront Preview",
    },
    state: {
      loadFailureTitle: "Unable to load this brand market",
      brandNotFound: "The brand could not be found",
      backToBrandStores: "Back to Brand Stores",
      launchingSoonTitle: "Launching Soon",
      launchingSoonDescription: "This brand market is being prepared and will open soon.",
    },
    preview: {
      internalPreview: "Internal Preview",
      publishedSnapshot: "Published Snapshot",
      previewDraft: "Preview Draft",
      draft: "Draft",
      description:
        "This route is rendering storefront data from the admin workflow and does not affect the public page until it is published.",
    },
    hero: {
      discoverBrand: "Discover the Brand",
      shopCollection: "Shop the Collection",
      browseProducts: "Browse Products",
      exploreCategories: "Explore Categories",
      exploreStories: "Explore Stories",
      shopCollections: "Shop Collections",
      viewCampaign: "View Campaign",
      shopOffers: "Shop Offers",
      startRoutine: "Start the Routine",
      exploreSolutions: "Explore Solutions",
      getOffer: "Get the Offer",
      seeAllDeals: "See All Deals",
      startShopping: "Start Shopping",
    },
    section: {
      brandPromiseEyebrow: "Brand Promise",
      customerVoicesEyebrow: "Customer Voices",
      faqEyebrow: "FAQ",
      brandValuesEyebrow: "Brand Values",
      curatedShelfEyebrow: "Curated Shelf",
      curatedCollectionsEyebrow: "Curated Collections",
      featuredCollectionEyebrow: "Featured Collection",
      featuredStoryEyebrow: "Featured Story",
      recommendedEyebrow: "Recommended",
      enterCollection: "Enter Collection",
      exploreCollection: "Explore Collection",
      collectionNavigationEyebrow: "Collection Navigation",
      exploreCategoriesEyebrow: "Explore Categories",
      brandCampaignsEyebrow: "Brand Campaigns",
      policiesEyebrow: "Policies",
      serviceSupportEyebrow: "Service & Support",
    },
    product: {
      liveOffer: "Live Offer",
      featuredProductEyebrow: "Featured Product",
      verifiedReviewSummary: "{{count}} verified customer reviews for this product",
      featuredProductDescription:
        "A featured pick in this journey with direct access to product details and checkout.",
      noReviews: "No reviews",
      leftCount: "{{count}} left",
      available: "Available",
      viewProduct: "View Product",
      addToCart: "Add to Cart",
      viewAll: "View All",
      deliverToLocation: "Deliver To Your Location",
    },
    banner: {
      exploreOffer: "Explore Offer",
      shopNow: "Shop Now",
      explore: "Explore",
    },
    cta: {
      learnMore: "Learn More",
    },
    template: {
      common: {
        faqTitle: "Frequently Asked Questions",
        policiesTitle: "Policies",
        serviceTitle: "Service & Support",
      },
      editorialHero: {
        promiseTitle: "Why This Brand",
        storyEyebrow: "Brand Story",
        storyTitle: "Brand Story",
        valuesTitle: "Brand Values",
        keyBenefitsEyebrow: "Key Benefits",
        keyBenefitsTitle: "What Shapes the Journey",
        categoryHubTitle: "Browse by Category",
        featuredCollectionsTitle: "Featured Collections",
        collectionNavigationTitle: "Start by Collection",
        bestSellersTitle: "Best Sellers",
        bannerAdsTitle: "Selected Offers",
        newArrivalsTitle: "New Arrivals",
        offerHighlightsEyebrow: "Highlights",
        offerHighlightsTitle: "Why Customers Choose It",
        recommendedTitle: "Recommended for You",
        socialProofTitle: "Trusted by Customers",
      },
      commerceGrid: {
        quickJumpTitle: "Shopping Shortcuts",
        quickJumpBestSellersLabel: "Best Sellers",
        quickJumpBestSellersDescription: "Shop high-demand picks",
        quickJumpCategoriesLabel: "Categories",
        quickJumpCategoriesDescription: "Start by taxonomy",
        promiseTitle: "Why shoppers start here",
        storyEyebrow: "Brand Story",
        storyTitle: "Brand Story",
        valuesTitle: "Experience Values",
        keyBenefitsEyebrow: "Shopping Advantages",
        keyBenefitsTitle: "How the Journey Works",
        categoryHubTitle: "Browse by Category",
        bestSellersTitle: "Best Sellers",
        bestSellersDescription: "The strongest performers for this brand",
        bannerAdsTitle: "Today’s Offers",
        newArrivalsTitle: "New Arrivals",
        collectionNavigationTitle: "Shop by Collection",
        recommendedTitle: "Recommended for You",
        offerHighlightsEyebrow: "Offer Highlights",
        offerHighlightsTitle: "Reasons to Buy",
        socialProofTitle: "Trust Signals",
      },
      storyCollection: {
        categoryHubTitle: "Explore Categories",
        promiseTitle: "Why this collection path works",
        storyEyebrow: "Editorial Story",
        storyTitle: "Editorial Story",
        valuesTitle: "Brand Values",
        keyBenefitsEyebrow: "Curated Advantages",
        keyBenefitsTitle: "What Guides This Story",
        featuredCollectionsTitle: "Featured Collections",
        collectionNavigationTitle: "Navigate Collections",
        recommendedTitle: "Curated Picks",
        bannerAdsTitle: "Stories & Offers",
        bestSellersTitle: "Best Sellers",
        newArrivalsTitle: "New Arrivals",
        offerHighlightsEyebrow: "Offer Highlights",
        offerHighlightsTitle: "Why Customers Choose It",
        socialProofTitle: "Testimonials & Proof",
      },
      campaignFocus: {
        promiseTitle: "Campaign spotlight",
        storyEyebrow: "Campaign Story",
        storyTitle: "Campaign Story",
        valuesTitle: "Brand Foundations",
        keyBenefitsEyebrow: "Campaign Pillars",
        keyBenefitsTitle: "What Drives Conversion",
        categoryHubTitle: "Browse by Category",
        featuredCollectionsTitle: "Campaign Collections",
        collectionNavigationTitle: "Jump by Collection",
        bannerAdsTitle: "Campaign Creatives",
        liveCampaignsTitle: "Live Campaigns",
        offerHighlightsEyebrow: "Campaign Value",
        offerHighlightsTitle: "What Makes This Offer Strong",
        recommendedTitle: "Campaign Picks",
        bestSellersTitle: "Best Sellers",
        newArrivalsTitle: "New Arrivals",
        socialProofTitle: "Proof Behind the Campaign",
      },
      routineSolution: {
        quickJumpTitle: "Routine Steps",
        categoryHubTitle: "Start by Category",
        promiseTitle: "How the routine flows",
        storyEyebrow: "Routine Story",
        storyTitle: "Routine Story",
        valuesTitle: "Brand Values",
        keyBenefitsEyebrow: "Routine Steps",
        keyBenefitsTitle: "Build the Routine",
        offerHighlightsEyebrow: "Expected Outcomes",
        offerHighlightsTitle: "Outcomes and Highlights",
        featuredCollectionsTitle: "Routine Collections",
        collectionNavigationTitle: "Start by Collection",
        bannerAdsTitle: "Supporting Offers",
        bestSellersTitle: "Best Sellers",
        newArrivalsTitle: "New Arrivals",
        recommendedTitle: "You May Also Like",
        socialProofTitle: "Real Results",
      },
      dealPromo: {
        promiseTitle: "Why this deal page converts",
        storyEyebrow: "Offer Story",
        storyTitle: "Offer Story",
        valuesTitle: "Brand Values",
        keyBenefitsEyebrow: "Storefront Advantages",
        keyBenefitsTitle: "Why This Offer Converts",
        categoryHubTitle: "Browse by Category",
        featuredCollectionsTitle: "Featured Collections",
        collectionNavigationTitle: "Shop by Collection",
        bannerAdsTitle: "Top Deals",
        bestDealPicksTitle: "Best Deal Picks",
        newArrivalsTitle: "New Arrivals",
        recommendedTitle: "You May Also Like",
        offerHighlightsEyebrow: "Value Highlights",
        offerHighlightsTitle: "Why These Deals Convert",
        socialProofTitle: "Trusted Deals",
      },
      categoryHub: {
        promiseTitle: "Shop the brand your way",
        storyEyebrow: "Category Story",
        storyTitle: "Category Story",
        valuesTitle: "Brand Values",
        keyBenefitsEyebrow: "Discovery Advantages",
        keyBenefitsTitle: "How Customers Start Here",
        allCategoriesTitle: "All Categories",
        collectionNavigationTitle: "Jump by Collection",
        bestSellersTitle: "Best Sellers",
        newArrivalsTitle: "New Arrivals",
        recommendedTitle: "Recommended Picks",
        recommendedDescription: "Begin with a recommended shelf before going deeper into the category map.",
        bannerAdsTitle: "Category Offers",
        offerHighlightsEyebrow: "Why Browse Here",
        offerHighlightsTitle: "Reasons to Explore",
        socialProofTitle: "Trust Signals",
      },
    },
    footer: {
      servicePortal: "Service Portal",
      navigate: "Navigate",
      follow: "Follow",
      privacyPolicy: "Privacy Policy",
      termsAndConditions: "Terms & Conditions",
    },
  },
  ar: {
    defaults: {
      brandStorefront: "سوق العلامة",
      collection: "مجموعة",
      collectionNumber: "المجموعة {{count}}",
      product: "منتج",
      category: "فئة",
      card: "بطاقة",
      stepNumber: "الخطوة {{count}}",
      value: "قيمة",
      link: "رابط",
      social: "اجتماعي",
      offer: "عرض",
      campaign: "حملة",
      policy: "سياسة",
      finalCtaAlt: "الدعوة الختامية للإجراء",
      brandHeroMediaAlt: "الوسائط الرئيسية للعلامة",
    },
    masthead: {
      catalog: "الكتالوج",
      collections: "المجموعات",
      bestSellers: "الأكثر مبيعاً",
      policies: "السياسات",
      support: "الدعم",
      brandStores: "كل المتاجر",
      navigationAria: "تنقل سوق العلامة",
      storefront: "سوق العلامة",
      storefrontPreview: "معاينة سوق العلامة",
    },
    state: {
      loadFailureTitle: "تعذر تحميل سوق العلامة",
      brandNotFound: "العلامة غير موجودة",
      backToBrandStores: "العودة إلى متاجر العلامات",
      launchingSoonTitle: "سيتم الإطلاق قريباً",
      launchingSoonDescription: "هذا السوق قيد التجهيز وسيتم فتحه قريباً.",
    },
    preview: {
      internalPreview: "معاينة داخلية",
      publishedSnapshot: "منشور",
      previewDraft: "قيد المعاينة",
      draft: "مسودة",
      description:
        "هذا العرض يظهر محتوى الواجهة من مسار الإدارة ولن ينعكس على الصفحة العامة إلا بعد النشر.",
    },
    hero: {
      discoverBrand: "اكتشف العلامة",
      shopCollection: "تسوق التشكيلة",
      browseProducts: "تصفح المنتجات",
      exploreCategories: "استكشف الفئات",
      exploreStories: "استكشف القصص",
      shopCollections: "تسوق المجموعات",
      viewCampaign: "شاهد الحملة",
      shopOffers: "تسوق العروض",
      startRoutine: "ابدأ الروتين",
      exploreSolutions: "استكشف الحلول",
      getOffer: "احصل على العرض",
      seeAllDeals: "شاهد كل التخفيضات",
      startShopping: "ابدأ التسوق",
    },
    section: {
      brandPromiseEyebrow: "وعد العلامة",
      customerVoicesEyebrow: "أصوات المتسوقين",
      faqEyebrow: "الأسئلة الشائعة",
      brandValuesEyebrow: "قيم العلامة",
      curatedShelfEyebrow: "مجموعة موصى بها",
      curatedCollectionsEyebrow: "مجموعات مختارة",
      featuredCollectionEyebrow: "المجموعة الرئيسية",
      featuredStoryEyebrow: "قصة موصى بها",
      recommendedEyebrow: "مقترح لك",
      enterCollection: "ادخل إلى المجموعة",
      exploreCollection: "استكشف المجموعة",
      collectionNavigationEyebrow: "تنقل المجموعات",
      exploreCategoriesEyebrow: "اكتشف الفئات",
      brandCampaignsEyebrow: "حملات العلامة",
      policiesEyebrow: "السياسات",
      serviceSupportEyebrow: "الخدمة والدعم",
    },
    product: {
      liveOffer: "عرض مباشر",
      featuredProductEyebrow: "اختيار مميز",
      verifiedReviewSummary: "{{count}} مراجعة موثوقة لهذا المنتج",
      featuredProductDescription:
        "اختيار مميز داخل هذه الرحلة مع وصول مباشر إلى التفاصيل والشراء.",
      noReviews: "بدون تقييمات",
      leftCount: "{{count}} متبقي",
      available: "متوفر",
      viewProduct: "عرض المنتج",
      addToCart: "أضف إلى السلة",
      viewAll: "عرض الكل",
      deliverToLocation: "التوصيل إلى موقعك",
    },
    banner: {
      exploreOffer: "استكشف العرض",
      shopNow: "تسوق الآن",
      explore: "استكشف",
    },
    cta: {
      learnMore: "اعرف المزيد",
    },
    template: {
      common: {
        faqTitle: "الأسئلة الشائعة",
        policiesTitle: "السياسات",
        serviceTitle: "الخدمة والدعم",
      },
      editorialHero: {
        promiseTitle: "فلسفة العلامة",
        storyEyebrow: "قصة العلامة",
        storyTitle: "قصة العلامة",
        valuesTitle: "قيم العلامة",
        keyBenefitsEyebrow: "مزايا رئيسية",
        keyBenefitsTitle: "كيف تقود الرحلة",
        categoryHubTitle: "تصفح حسب الفئة",
        featuredCollectionsTitle: "مجموعات مميزة",
        collectionNavigationTitle: "ابدأ من مجموعة",
        bestSellersTitle: "الأكثر مبيعاً",
        bannerAdsTitle: "عروض مختارة",
        newArrivalsTitle: "وصل حديثاً",
        offerHighlightsEyebrow: "أبرز الميزات",
        offerHighlightsTitle: "لماذا يختاره العملاء",
        recommendedTitle: "مختارات لك",
        socialProofTitle: "يثق به العملاء",
      },
      commerceGrid: {
        quickJumpTitle: "اختصارات التسوق",
        quickJumpBestSellersLabel: "الأكثر مبيعاً",
        quickJumpBestSellersDescription: "الأكثر طلباً الآن",
        quickJumpCategoriesLabel: "الفئات",
        quickJumpCategoriesDescription: "ابدأ من التصنيف",
        promiseTitle: "لماذا يبدأ المتسوق من هنا",
        storyEyebrow: "سرد التجربة",
        storyTitle: "سرد التجربة",
        valuesTitle: "قيم التجربة",
        keyBenefitsEyebrow: "مزايا التسوق",
        keyBenefitsTitle: "كيف تُبنى الرحلة",
        categoryHubTitle: "تصفح حسب الفئة",
        bestSellersTitle: "الأكثر مبيعاً",
        bestSellersDescription: "المنتجات الأكثر طلباً",
        bannerAdsTitle: "عروض اليوم",
        newArrivalsTitle: "وصل حديثاً",
        collectionNavigationTitle: "ابدأ من مجموعة",
        recommendedTitle: "مختارات لك",
        offerHighlightsEyebrow: "أبرز المزايا",
        offerHighlightsTitle: "أسباب الشراء",
        socialProofTitle: "مؤشرات الثقة",
      },
      storyCollection: {
        categoryHubTitle: "استكشف الفئات",
        promiseTitle: "لماذا يعمل هذا المسار",
        storyEyebrow: "السرد التحريري",
        storyTitle: "السرد التحريري",
        valuesTitle: "قيم العلامة",
        keyBenefitsEyebrow: "مفاتيح الاختيار",
        keyBenefitsTitle: "ما الذي يوجه هذه القصة",
        featuredCollectionsTitle: "المجموعات الرئيسية",
        collectionNavigationTitle: "تنقل بين المجموعات",
        recommendedTitle: "مختارات من المحرر",
        bannerAdsTitle: "قصص وعروض",
        bestSellersTitle: "الأكثر مبيعاً",
        newArrivalsTitle: "وصل حديثاً",
        offerHighlightsEyebrow: "أسباب الاختيار",
        offerHighlightsTitle: "لماذا يختارها العملاء",
        socialProofTitle: "توصيات وتجارب",
      },
      campaignFocus: {
        promiseTitle: "فكرة الحملة",
        storyEyebrow: "قصة الحملة",
        storyTitle: "قصة الحملة",
        valuesTitle: "مرتكزات العلامة",
        keyBenefitsEyebrow: "مرتكزات العرض",
        keyBenefitsTitle: "ما الذي يدفع التحويل",
        categoryHubTitle: "تصفح حسب الفئة",
        featuredCollectionsTitle: "مجموعات الحملة",
        collectionNavigationTitle: "انتقل حسب المجموعة",
        bannerAdsTitle: "إعلانات الحملة",
        liveCampaignsTitle: "حملات مباشرة",
        offerHighlightsEyebrow: "أسباب الحملة",
        offerHighlightsTitle: "ما الذي يميز العرض",
        recommendedTitle: "منتجات مرتبطة بالحملة",
        bestSellersTitle: "الأكثر مبيعاً",
        newArrivalsTitle: "وصل حديثاً",
        socialProofTitle: "الثقة في الحملة",
      },
      routineSolution: {
        quickJumpTitle: "خطوات الروتين",
        categoryHubTitle: "ابدأ حسب الفئة",
        promiseTitle: "كيف تنساب الرحلة",
        storyEyebrow: "قصة الروتين",
        storyTitle: "قصة الروتين",
        valuesTitle: "قيم العلامة",
        keyBenefitsEyebrow: "خطوات الروتين",
        keyBenefitsTitle: "ابنِ الحل خطوة بخطوة",
        offerHighlightsEyebrow: "نتائج متوقعة",
        offerHighlightsTitle: "نتائج ومزايا",
        featuredCollectionsTitle: "المجموعات المناسبة",
        collectionNavigationTitle: "ابدأ من المجموعة",
        bannerAdsTitle: "عروض داعمة",
        bestSellersTitle: "الأكثر مبيعاً",
        newArrivalsTitle: "وصل حديثاً",
        recommendedTitle: "قد يعجبك أيضاً",
        socialProofTitle: "نتائج حقيقية",
      },
      dealPromo: {
        promiseTitle: "لماذا ينجح هذا العرض",
        storyEyebrow: "قصة العرض",
        storyTitle: "قصة العرض",
        valuesTitle: "قيم العلامة",
        keyBenefitsEyebrow: "مزايا المتجر",
        keyBenefitsTitle: "لماذا يتحول هذا العرض",
        categoryHubTitle: "تصفح حسب الفئة",
        featuredCollectionsTitle: "مجموعات مميزة",
        collectionNavigationTitle: "تصفح حسب المجموعة",
        bannerAdsTitle: "أفضل العروض",
        bestDealPicksTitle: "أفضل الصفقات",
        newArrivalsTitle: "وصل حديثاً",
        recommendedTitle: "قد يعجبك أيضاً",
        offerHighlightsEyebrow: "القيمة المضافة",
        offerHighlightsTitle: "لماذا هذا العرض قوي",
        socialProofTitle: "الصفقات الموثوقة",
      },
      categoryHub: {
        promiseTitle: "تسوق العلامة بطريقتك",
        storyEyebrow: "قصة التصنيف",
        storyTitle: "قصة التصنيف",
        valuesTitle: "قيم العلامة",
        keyBenefitsEyebrow: "مزايا الاستكشاف",
        keyBenefitsTitle: "كيف يبدأ العميل",
        allCategoriesTitle: "كل الفئات",
        collectionNavigationTitle: "ابدأ من مجموعة",
        bestSellersTitle: "الأكثر مبيعاً",
        newArrivalsTitle: "وصل حديثاً",
        recommendedTitle: "مختارات سريعة",
        recommendedDescription: "ابدأ من رف موصى به قبل التعمق في الفئات.",
        bannerAdsTitle: "عروض حسب الفئة",
        offerHighlightsEyebrow: "ما الذي يميز التسوق هنا",
        offerHighlightsTitle: "أسباب الاستكشاف",
        socialProofTitle: "دلائل الثقة",
      },
    },
    footer: {
      servicePortal: "بوابة الخدمة",
      navigate: "التنقل",
      follow: "تواصل معنا",
      privacyPolicy: "سياسة الخصوصية",
      termsAndConditions: "الشروط والأحكام",
    },
  },
};

const getPathValue = (source, key) =>
  String(key || "")
    .split(".")
    .filter(Boolean)
    .reduce((value, segment) => (value && typeof value === "object" ? value[segment] : undefined), source);

const interpolate = (template, variables = {}) =>
  String(template || "").replace(/\{\{\s*([\w.]+)\s*\}\}/g, (_, key) => {
    const value = getPathValue(variables, key);
    return value === undefined || value === null ? "" : String(value);
  });

export const normalizeBrandTemplateLanguage = (language) =>
  String(language || "en").toLowerCase().startsWith("ar") ? "ar" : "en";

export const getBrandTemplateCopy = (language, key, variables = {}) => {
  const normalizedLanguage = normalizeBrandTemplateLanguage(language);
  const localizedValue = getPathValue(COPY[normalizedLanguage], key);
  const fallbackValue = getPathValue(COPY.en, key);
  const resolved = localizedValue ?? fallbackValue ?? key;
  return typeof resolved === "string" ? interpolate(resolved, variables) : resolved;
};

export default getBrandTemplateCopy;
